version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./backend:/usr/share/nginx/html/backend:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro   # monta la config correcta de nginx
    depends_on:
      - php
      - db
    networks:
      - helpdesk-net

  php:
    build: .
    volumes:
      - ./backend:/var/www/html/backend
      - ./frontend:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: helpdesk
      DB_USER: root
      DB_PASSWORD: root
    networks:
      - helpdesk-net

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: helpdesk
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - helpdesk-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - helpdesk-net

networks:
  helpdesk-net:
    driver: bridge

volumes:
  mysql_data:
