version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/frontend  # Cambiado de /html a /frrontend
      - ./backend:/var/www/backend    # Nueva ruta para PHP
    depends_on:
      - php
      - db
    networks:
      - helpdesk-net

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/backend  # Cambiado para coincidir con Nginx
    environment:
      - DB_HOST=db
      - DB_NAME=helpdesk
      - DB_USER=root
      - DB_PASSWORD=root
    networks:
      - helpdesk-net

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: helpdesk
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - helpdesk-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - helpdesk-net

networks:
  helpdesk-net:
    driver: bridge

volumes:
  mysql_data:  # Persistencia de datos de MySQL