apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: frontend-html
          mountPath: /var/www/html/index.html
          subPath: index.html
        - name: frontend-css
          mountPath: /var/www/html/css/styles.css
          subPath: styles.css
        - name: frontend-js
          mountPath: /var/www/html/js/app.js
          subPath: app.js
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap
      - name: frontend-html
        configMap:
          name: frontend-config
          items:
          - key: index.html
            path: index.html
      - name: frontend-css
        configMap:
          name: frontend-config
          items:
          - key: styles.css
            path: styles.css
      - name: frontend-js
        configMap:
          name: frontend-config
          items:
          - key: app.js
            path: app.js
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080