apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: admin-html
          mountPath: /var/www/html/admin/index.html
          subPath: index.html
        - name: admin-css
          mountPath: /var/www/html/admin/styles.css
          subPath: styles.css
        - name: cliente-html
          mountPath: /var/www/html/cliente/index.html
          subPath: index.html
        - name: cliente-css
          mountPath: /var/www/html/cliente/styles.css
          subPath: styles.css
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap
      - name: admin-html
        configMap:
          name: frontend-admin-config
          items:
          - key: index.html
            path: index.html
      - name: admin-css
        configMap:
          name: frontend-admin-config
          items:
          - key: styles.css
            path: styles.css
      - name: cliente-html
        configMap:
          name: frontend-cliente-config
          items:
          - key: index.html
            path: index.html
      - name: cliente-css
        configMap:
          name: frontend-cliente-config
          items:
          - key: styles.css
            path: styles.css

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080