apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php:8.2-fpm  # Cambiado a imagen FPM
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: php-source
          mountPath: /var/www/html
      volumes:
      - name: php-source
        configMap:
          name: php-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  index.php: |
    <?php
    header('Content-Type: application/json');

    $conexion = new mysqli("mysql-service", "root", "root", "helpdesk");

    if ($conexion->connect_error) {
        http_response_code(500);
        echo json_encode(["error" => "Error de conexión: " . $conexion->connect_error]);
        exit;
    }

    $sql = "SELECT * FROM tickets";
    $resultado = $conexion->query($sql);

    $tickets = [];

    if ($resultado->num_rows > 0) {
        while ($fila = $resultado->fetch_assoc()) {
            $tickets[] = $fila;
        }
    }

    echo json_encode($tickets);
    $conexion->close();
    ?>